### PR TITLE
Prepare for packaging

### LINKED ISSUE #4: Provide a shared library with a proper SONAME
I see that Neovim v0.1.4 now has a hard dependency on libmpack (even though it seems to only be used during testing).  Could this start building a shared library with some ABI guarantees?

I'd like to get this packaged for Debian so that I can keep up to date with Neovim's packaging, but I'd prefer to have a shared library to work with.

### PR DESCRIPTION
**Pull request by tarruda**
Close #4 

@jamessan can you check if I'm missing anything?

### CODE REVIEW

**Comment by jamessan** [comment]
I haven't had a chance to test it out yet, but it looks like there still isn't a shared library being built and you're not providing ABI/API guarantees yet (based on the 0.0.0 SONAME, so maybe I'm just reading into that too much).

For the shared library aspect, is there an intention to eventually provide a shared library or does the C code exist solely for the use of the Lua bindings?

**Comment by tarruda** [comment]
> I haven't had a chance to test it out yet, but it looks like there still isn't a shared library being built and you're not providing ABI/API guarantees yet (based on the 0.0.0 SONAME, so maybe I'm just reading into that too much).

The shared library is being built now that I add -rpath to `libtool --link`. Also what kind of guarantee are you looking for? I don't plan on making API changes anytime soon, and if I do there will be changes in the major/minor versions. Also, every change made to source code will incur in a change in libtool version. Is that enough?

With this PR you can prepare a dir for packaging with a simple `make DESTDIR=$DESTDIR config=release install`

> For the shared library aspect, is there an intention to eventually provide a shared library or does the C code exist solely for the use of the Lua bindings?

My goal is to make this a general purpose serialization library to C, even if it is friendly to be used in a language binding.

**Comment by jamessan** [comment]
> The shared library is being built now that I add -rpath to libtool --link.

:+1:  I'm not that familiar with the use of libtool, so I didn't realize that `-rpath` would effect that change.

> I don't plan on making API changes anytime soon, and if I do there will be changes in the major/minor versions. Also, every change made to source code will incur in a change in libtool version. Is that enough?

That's perfect.

Looks good to me.  Thanks!  I look forward to a release with this so I can get neovim updated in Debian. :)

**Comment by glensc** [comment]
could you tag a release so the changes since 1.0.2 in master get included?

**Pull request merged**
